# https://docs.docker.com/ci-cd/github-actions/
# https://www.docker.com/blog/best-practices-for-using-docker-hub-for-ci-cd/  


name: Failing CI

on:
  push:
    branches:
      - 'main'
      - 'etapa-**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Copiar arquivo para .env
        run: |
          cp .env.example .env
          cp .env.example library_back/.env
      
      - name: Levantar todos containers e executar Testes de API e Web
        run: |
          docker-compose up -d --build
          docker logs library-api
          echo ">>>>"
          docker logs library-web
          echo ">>>>"

          docker exec library-api /bin/bash -c "python manage.py migrate"
          
          docker exec library-api /bin/bash -c "./scripts/test-integ.sh"
          docker exec library-web /bin/bash -c "npm run test"

# Tentar encontrar outr GH Action pra docker compose
